---
title: Monoso
timezone: America/Los_Angeles
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
    permalink: ":title"
  services:
    title: Services
    output: true
    permalink: ":title"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    description:
description: A boutique web development firm focused on building simple and sustainable solutions, specializing in Ruby on Rails, Ember.js, Shopify, and Wordpress.
url: http://www.monoso.co
logo: "/img/monoso-logo.png"
twitter:
  username: monoso_co
social:
  links:
  - https://twitter.com/monoso_co
name:  Monoso
highlighter: rouge
markdown: kramdown
permalink: ":title"
gems:
- jemoji
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
sass:
  sass_dir: _sass
  style: compressed
