---
title: Brett Codes
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
    permalink: ":title"
  services:
    title: Services
    output: true
    permalink: ":title"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    description: 
description: Programming screencasts, tutorials, and blog posts by Brett Chalupa.
url: https://code.brettchalupa.com
logo: "/img/brett.jpg"
twitter:
  username: brettchalupa
social:
  links:
  - https://www.youtube.com/channel/UCQXaIyeRqHjK9EK41b8J3yQ
  - https://github.com/brettchalupa
name: Brett Codes
highlighter: rouge
markdown: kramdown
permalink: ":title"
plugins:
- jemoji
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
sass:
  sass_dir: _sass
  style: compressed
